name: Production - Build & Deploy
on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-vite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: .
          target: /home/kunalshah5301/backend-app

      - name: Restart Node App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/kunalshah5301/backend-app
            sudo docker compose up -d --build backend
            sudo docker system prune -af
